all:
	sudo mkdir -p /home/cogroid/local/libunistring/x64
	cd ../../; \
	./configure \
	--prefix=/home/cogroid/local/libunistring/x64 \
	--docdir=/home/cogroid/local/libunistring/x64/share/doc/libunistring-0.9.9; \
	make

install:
	sudo sh -c 'cd ../../; \
	make install;'


